language: perl
sudo: false
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.16"
   - "5.18"
   - "5.20"
   - "5.22"
install:
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - cpanm --quiet --notest --installdeps .
   - cpanm -nq Devel::Cover::Report::Coveralls Test::PerlTidy
script:
   - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
   - cover
after_success:
  - cover -report coveralls
