language: perl
sudo: false
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.16"
   - "5.18"
   - "5.20"
   - "5.22"
   - "5.24"
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
  allow_failures:
    - perl: blead
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
